# fly.toml file generated for gmaimon-auraair on 2021-11-30T11:02:48+02:00

app = "gmaimon-auraair"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
PORT = "8080"
NODE_ENV = "production"
SESSION_SECRET="gmaimonAuraAir!"

[deploy]
  release_command = "npx prisma migrate deploy"

[experimental]
allowed_public_ports = []
auto_rollback = true
private_network = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 75
    soft_limit = 50
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
